name: Everyday

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *' # Triggers at 12 am UTC every day

jobs:
  everyday_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install fs path moment csv-parser

      - name: Install Telegram dependencies
        run: npm install node-telegram-bot-api

      - name: Run Code
        run: node hbd.js
