name: Everyday

on:
  workflow_dispatch:
  
  schedule:
    - cron: '5 0 * * *' # Triggers at 5:35 am Indian Time every day

jobs:
  everyday_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install fs path moment csv-parser dotenv

      - name: Install Telegram dependencies
        run: npm install node-telegram-bot-api telegram-format

      - name: Run Birthday Code
        run: node hbd.js

      - name: Run Aniversary Code
        run: node Ani.js

