name: monthly

on:
  workflow_dispatch:

  schedule:
    - cron: '5 0 1 * *' # Triggers at 5:35 am Indian time every month

jobs:
  monthly_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install fs path moment csv-parser

      - name: Install Telegram dependencies
        run: npm install node-telegram-bot-api

      - name: Run Test
        run: node monthly.js
